import type { Company } from '../modules/company/interfaces/company.interface';

export const mockCompanies: Company[] = [
  {
    id: '1',
    name: 'TechCorp',
    description: 'Leading provider of tech conferences and workshops across the country',
    email: 'info@techcorp.com',
    website: 'https://techcorp.com',
    logo: 'https://randomuser.me/api/portraits/men/1.jpg',
    coverImage: '/bustling-tech-summit.png',
    location: 'San Francisco, CA',
    createdAt: '2023-01-15T09:00:00Z',
    updatedAt: '2023-06-20T14:30:00Z',
    ownerId: 'user_1',
    eventCount: 42,
    subscriberCount: 1250
  },
  {
    id: '2',
    name: 'SoundWave Productions',
    description: 'Music festival and concert organizers with a passion for live performances',
    email: 'events@soundwave.com',
    website: 'https://soundwave.com',
    logo: 'https://randomuser.me/api/portraits/women/2.jpg',
    coverImage: '/vibrant-festival-crowd.png',
    location: 'Austin, TX',
    createdAt: '2023-02-10T11:20:00Z',
    updatedAt: '2023-07-05T16:45:00Z',
    ownerId: 'user_2',
    eventCount: 78,
    subscriberCount: 3400
  },
  {
    id: '3',
    name: 'Metropolitan Gallery',
    description: 'Art exhibitions and cultural events in the heart of the city',
    email: 'gallery@metropolitan.com',
    website: 'https://metropolitan.com',
    logo: 'https://randomuser.me/api/portraits/women/3.jpg',
    coverImage: '/modern-art-exhibition.png',
    location: 'New York, NY',
    createdAt: '2023-03-05T10:15:00Z',
    updatedAt: '2023-08-12T09:30:00Z',
    ownerId: 'user_3',
    eventCount: 35,
    subscriberCount: 890
  },
  {
    id: '4',
    name: 'Venture Accelerator',
    description: 'Startup and entrepreneurship events focused on innovation and growth',
    email: 'hello@venture.com',
    website: 'https://venture.com',
    logo: 'https://randomuser.me/api/portraits/men/4.jpg',
    coverImage: '/bustling-startup-summit.png',
    location: 'Boston, MA',
    createdAt: '2023-04-20T14:00:00Z',
    updatedAt: '2023-09-01T11:20:00Z',
    ownerId: 'user_4',
    eventCount: 29,
    subscriberCount: 1560
  },
  {
    id: '5',
    name: 'Gourmet Events',
    description: 'Food festivals and culinary experiences featuring top chefs',
    email: 'taste@gourmet.com',
    website: 'https://gourmet.com',
    logo: 'https://randomuser.me/api/portraits/women/5.jpg',
    coverImage: '/bustling-startup-summit.png',
    location: 'Chicago, IL',
    createdAt: '2023-05-15T08:45:00Z',
    updatedAt: '2023-10-10T15:30:00Z',
    ownerId: 'user_5',
    eventCount: 52,
    subscriberCount: 2100
  },
  {
    id: '6',
    name: 'HealthFirst Foundation',
    description: 'Charity runs and wellness events promoting healthy lifestyles',
    email: 'info@healthfirst.org',
    website: 'https://healthfirst.org',
    logo: 'https://randomuser.me/api/portraits/men/6.jpg',
    coverImage: '/bustling-startup-summit.png',
    location: 'Seattle, WA',
    createdAt: '2023-06-10T13:30:00Z',
    updatedAt: '2023-11-05T10:15:00Z',
    ownerId: 'user_6',
    eventCount: 18,
    subscriberCount: 750
  },
  {
    id: '7',
    name: 'Creative Lens Studios',
    description: 'Photography workshops and exhibitions for all skill levels',
    email: 'hello@creativelens.com',
    logo: 'https://randomuser.me/api/portraits/women/7.jpg',
    coverImage: '/placeholder.svg?height=128&width=384&query=photography workshop',
    location: 'Portland, OR',
    createdAt: '2023-07-22T09:20:00Z',
    updatedAt: '2023-12-15T14:40:00Z',
    ownerId: 'user_7',
    eventCount: 24,
    subscriberCount: 680
  },
  {
    id: '8',
    name: 'Future Chain',
    description: 'Blockchain and cryptocurrency conferences with industry leaders',
    email: 'contact@futurechain.io',
    website: 'https://futurechain.io',
    logo: 'https://randomuser.me/api/portraits/men/8.jpg',
    coverImage: '/placeholder.svg?height=128&width=384&query=blockchain conference',
    location: 'Miami, FL',
    createdAt: '2023-08-05T11:10:00Z',
    updatedAt: '2024-01-20T16:30:00Z',
    ownerId: 'user_8',
    eventCount: 31,
    subscriberCount: 2800
  },
  {
    id: '9',
    name: 'Future Immersive',
    description: 'Virtual reality expos and demonstrations of cutting-edge technology',
    email: 'info@futureimmersive.com',
    website: 'https://futureimmersive.com',
    logo: 'https://randomuser.me/api/portraits/men/9.jpg',
    coverImage: '/placeholder.svg?height=128&width=384&query=virtual reality expo',
    location: 'Los Angeles, CA',
    createdAt: '2023-09-18T15:45:00Z',
    updatedAt: '2024-02-10T09:50:00Z',
    ownerId: 'user_9',
    eventCount: 15,
    subscriberCount: 1950
  },
  {
    id: '10',
    name: 'Mindful Living',
    description: 'Yoga retreats and wellness workshops in serene natural settings',
    email: 'hello@mindfulliving.com',
    website: 'https://mindfulliving.com',
    logo: 'https://randomuser.me/api/portraits/women/10.jpg',
    coverImage: '/placeholder.svg?height=128&width=384&query=yoga retreat',
    location: 'Sedona, AZ',
    createdAt: '2023-10-12T10:30:00Z',
    updatedAt: '2024-03-05T13:20:00Z',
    ownerId: 'user_10',
    eventCount: 22,
    subscriberCount: 1100
  },
  {
    id: '11',
    name: 'Independent Cinema Group',
    description: 'Film festivals showcasing independent filmmakers from around the world',
    email: 'films@independentcinema.org',
    logo: 'https://randomuser.me/api/portraits/men/11.jpg',
    coverImage: '/placeholder.svg?height=128&width=384&query=film festival',
    location: 'Park City, UT',
    createdAt: '2023-11-08T12:15:00Z',
    updatedAt: '2024-04-15T11:40:00Z',
    ownerId: 'user_11',
    eventCount: 8,
    subscriberCount: 720
  },
  {
    id: '12',
    name: 'Tech for Change',
    description: 'Hackathons and coding events focused on social impact projects',
    email: 'hello@techforchange.org',
    website: 'https://techforchange.org',
    logo: 'https://randomuser.me/api/portraits/women/12.jpg',
    coverImage: '/placeholder.svg?height=128&width=384&query=hackathon',
    location: 'Denver, CO',
    createdAt: '2023-12-20T09:40:00Z',
    updatedAt: '2024-05-10T15:10:00Z',
    ownerId: 'user_12',
    eventCount: 12,
    subscriberCount: 950
  },
  {
    id: '13',
    name: 'Downtown Association',
    description: 'Community events and farmers markets bringing locals together',
    email: 'info@downtownassociation.org',
    logo: 'https://randomuser.me/api/portraits/men/13.jpg',
    coverImage: '/placeholder.svg?height=128&width=384&query=farmers market',
    location: 'Burlington, VT',
    createdAt: '2024-01-15T14:20:00Z',
    updatedAt: '2024-06-01T10:30:00Z',
    ownerId: 'user_13',
    eventCount: 45,
    subscriberCount: 520
  },
  {
    id: '14',
    name: 'Galaxy Entertainment',
    description: 'Science fiction conventions and cosplay events for fans of all ages',
    email: 'events@galaxyent.com',
    website: 'https://galaxyent.com',
    logo: 'https://randomuser.me/api/portraits/women/14.jpg',
    coverImage: '/placeholder.svg?height=128&width=384&query=sci-fi convention',
    location: 'Atlanta, GA',
    createdAt: '2024-02-10T11:50:00Z',
    updatedAt: '2024-07-05T13:45:00Z',
    ownerId: 'user_14',
    eventCount: 17,
    subscriberCount: 3200
  },
  {
    id: '15',
    name: 'Career Connect',
    description: 'Job fairs and networking events connecting professionals with opportunities',
    email: 'info@careerconnect.com',
    website: 'https://careerconnect.com',
    logo: 'https://randomuser.me/api/portraits/men/15.jpg',
    coverImage: '/placeholder.svg?height=128&width=384&query=job fair',
    location: 'Dallas, TX',
    createdAt: '2024-03-05T09:15:00Z',
    updatedAt: '2024-08-12T16:20:00Z',
    ownerId: 'user_15',
    eventCount: 28,
    subscriberCount: 1750
  }
];
