import { AuthProvider, NotificationChannel, User } from '../modules/user/interfaces/user.interface';

export const mockUsers: User[] = [
  {
    id: 'user_1',
    name: 'Alice Johnson',
    email: 'alice.johnson@example.com',
    avatar: 'https://i.pravatar.cc/150?img=11',
    bio: 'Marketing specialist and event host.',
    role: 'USER',
    emailVerified: true,
    showInAttendeeList: true,
    authProvider: AuthProvider.EMAIL,
    eventReminderChannel: NotificationChannel.EMAIL,
    ticketPurchaseChannel: NotificationChannel.IN_APP,
    newCommentChannel: NotificationChannel.BOTH,
    companyUpdateChannel: NotificationChannel.EMAIL
  },
  {
    id: 'user_2',
    name: 'Bob Marley',
    email: 'bob.marley@example.com',
    avatar: 'https://i.pravatar.cc/150?img=12',
    bio: 'Musician and frequent concert attendee.',
    role: 'USER',
    emailVerified: false,
    showInAttendeeList: false,
    authProvider: AuthProvider.GOOGLE,
    eventReminderChannel: NotificationChannel.NONE,
    ticketPurchaseChannel: NotificationChannel.NONE,
    newCommentChannel: NotificationChannel.EMAIL,
    companyUpdateChannel: NotificationChannel.IN_APP
  },
  {
    id: 'user_3',
    name: 'Cathy Smith',
    email: 'cathy.smith@example.com',
    avatar: 'https://i.pravatar.cc/150?img=13',
    bio: 'Event planner from London.',
    role: 'ADMIN',
    emailVerified: true,
    showInAttendeeList: false,
    authProvider: AuthProvider.EMAIL,
    eventReminderChannel: NotificationChannel.BOTH,
    ticketPurchaseChannel: NotificationChannel.BOTH,
    newCommentChannel: NotificationChannel.IN_APP,
    companyUpdateChannel: NotificationChannel.BOTH
  },
  {
    id: 'user_4',
    name: 'Daniel Wu',
    email: 'daniel.wu@example.com',
    avatar: 'https://i.pravatar.cc/150?img=14',
    bio: 'Loves tech meetups and hackathons.',
    role: 'USER',
    emailVerified: true,
    showInAttendeeList: true,
    authProvider: AuthProvider.GOOGLE,
    eventReminderChannel: NotificationChannel.EMAIL,
    ticketPurchaseChannel: NotificationChannel.BOTH,
    newCommentChannel: NotificationChannel.NONE,
    companyUpdateChannel: NotificationChannel.NONE
  },
  {
    id: 'user_5',
    name: 'Ella Brown',
    email: 'ella.brown@example.com',
    avatar: 'https://i.pravatar.cc/150?img=15',
    bio: 'CEO at StartNext.',
    role: 'ADMIN',
    emailVerified: true,
    showInAttendeeList: false,
    authProvider: AuthProvider.EMAIL,
    eventReminderChannel: NotificationChannel.BOTH,
    ticketPurchaseChannel: NotificationChannel.BOTH,
    newCommentChannel: NotificationChannel.BOTH,
    companyUpdateChannel: NotificationChannel.BOTH
  },
  {
    id: 'user_6',
    name: 'Frank Müller',
    email: 'frank.muller@example.com',
    avatar: 'https://i.pravatar.cc/150?img=16',
    bio: 'German developer exploring the UK tech scene.',
    role: 'USER',
    emailVerified: false,
    showInAttendeeList: true,
    authProvider: AuthProvider.EMAIL,
    eventReminderChannel: NotificationChannel.NONE,
    ticketPurchaseChannel: NotificationChannel.IN_APP,
    newCommentChannel: NotificationChannel.IN_APP,
    companyUpdateChannel: NotificationChannel.EMAIL
  },
  {
    id: 'user_7',
    name: 'Grace O’Neil',
    email: 'grace.oneil@example.com',
    avatar: 'https://i.pravatar.cc/150?img=17',
    bio: 'Workshop organizer and digital artist.',
    role: 'USER',
    emailVerified: true,
    showInAttendeeList: true,
    authProvider: AuthProvider.GOOGLE,
    eventReminderChannel: NotificationChannel.BOTH,
    ticketPurchaseChannel: NotificationChannel.BOTH,
    newCommentChannel: NotificationChannel.EMAIL,
    companyUpdateChannel: NotificationChannel.BOTH
  },
  {
    id: 'user_8',
    name: 'Harry Tanaka',
    email: 'harry.tanaka@example.com',
    avatar: 'https://i.pravatar.cc/150?img=18',
    bio: 'Travel blogger attending global events.',
    role: 'USER',
    emailVerified: false,
    showInAttendeeList: false,
    authProvider: AuthProvider.GOOGLE,
    eventReminderChannel: NotificationChannel.NONE,
    ticketPurchaseChannel: NotificationChannel.NONE,
    newCommentChannel: NotificationChannel.NONE,
    companyUpdateChannel: NotificationChannel.NONE
  },
  {
    id: 'user_9',
    name: 'Isabella Rossi',
    email: 'isabella.rossi@example.com',
    avatar: 'https://i.pravatar.cc/150?img=19',
    bio: 'Italian entrepreneur in tech conferences.',
    role: 'USER',
    emailVerified: true,
    showInAttendeeList: true,
    authProvider: AuthProvider.EMAIL,
    eventReminderChannel: NotificationChannel.EMAIL,
    ticketPurchaseChannel: NotificationChannel.BOTH,
    newCommentChannel: NotificationChannel.BOTH,
    companyUpdateChannel: NotificationChannel.EMAIL
  },
  {
    id: 'user_10',
    name: 'Jack Li',
    email: 'jack.li@example.com',
    avatar: 'https://i.pravatar.cc/150?img=20',
    bio: 'Backend engineer with a love for speaking.',
    role: 'ADMIN',
    emailVerified: true,
    showInAttendeeList: true,
    authProvider: AuthProvider.GOOGLE,
    eventReminderChannel: NotificationChannel.IN_APP,
    ticketPurchaseChannel: NotificationChannel.IN_APP,
    newCommentChannel: NotificationChannel.EMAIL,
    companyUpdateChannel: NotificationChannel.BOTH
  }
];
